[[headers]]
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Xss-Protection = "1; mode=block;
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
